name: Linkwatch CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true

    - name: Verify dependencies
      run: go mod verify

    - name: Run linter
      run: |
        go install golang.org/x/lint/golint@latest
        golint -set_exit_status ./...

    - name: Run vet
      run: go vet ./...

    - name: Run tests
      run: go test -v -race -coverprofile=coverage.out ./...

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella

  build:
    name: Build and Verify
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true

    - name: Build application
      run: go build -v ./...

    - name: Build Docker image
      run: docker build -t linkwatch:test .

    - name: Test Docker image
      run: |
        # Start container in background
        docker run -d --name linkwatch-test -p 8080:8080 linkwatch:test
        
        # Wait for service to start
        sleep 10
        
        # Test health endpoint
        curl -f http://localhost:8080/healthz || exit 1
        
        # Clean up
        docker stop linkwatch-test
        docker rm linkwatch-test
